let modeloJson = [
    {
      id: 1,
      name: 'Camiseta Skunk-Doo',
      img: 'img/Camisa01.png',
      price: 20.19,
      sizes: ['malha', 'algodão', 'dry'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 2,
      name: 'Camiseta Chronic',
      img: 'img/Camisa02.png',
      price: 18.0,
      sizes: ['algodão', 'malha', 'dry'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 3,
      name: 'Camiseta Verde',
      img: 'img/Camisa03.png',
      price: 17.45,
      sizes: ['dry', 'malha', 'algodão'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 4,
      name: 'Camiseta Branca',
      img: 'img/Camisa04.png',
      price: 19.77,
      sizes: ['algodão', 'malha', 'dry'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 5,
      name: 'Camiseta Azul',
      img: 'img/Camisa05.png',
      price: 21.43,
      sizes: ['malha', 'algodão', 'dry'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 6,
      name: 'Camiseta Roxa',
      img: 'img/Camisa06.png',
      price: 18.55,
      sizes: ['malha', 'dry', 'algodão'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 7,
      name: 'Camiseta Vermelha',
      img: 'img/Camisa07.png',
      price: 22.36,
      sizes: ['malha', 'dry', 'dry'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 8,
      name: 'Camiseta Preta',
      img: 'img/Camisa08.png',
      price: 22.36,
      sizes: ['malha', 'dry', 'dry'],
      description: 'Blusa Básica Manga Curta',
    },
    {
      id: 9,
      name: 'Camiseta Preta',
      img: 'img/Camisa09.png',
      price: 22.36,
      sizes: ['malha', 'dry', 'dry'],
      description: 'Blusa Básica Manga Curta',
    }
]